name = "app"
uuid = "20595b51-8275-4fc6-af08-9ad61d7e3192"
version = "0.1.0"
authors = ["johndoe "]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
BenchmarkTools = "1.6.3"
CSV = "0.10.15"
DataFrames = "1.8.1"
OrdinaryDiffEq = "6.103.0"
Plots = "1.41.2"
Revise = "3.12.3"
